// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/bethojunior/go-blog/internal/handlers"
	"github.com/bethojunior/go-blog/internal/repository"
	"github.com/bethojunior/go-blog/internal/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUserHandler(db *gorm.DB) *handlers.UserHandler {
	userRepository := repository.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	return userHandler
}
